### ISSUE TITLE
No sound for HE-AAC v2 services (with Parametric Stereo)

### ISSUE THREAD

**Issue by andimik** [tomneda/DABstar#16] opened 2024-10-04 08:46 UTC
Using `DABstar-2.6.0-x86_64.AppImage` under Linux Mint, on all services with HE-AAC v2 codec the sound disappears after around 1 second (but SLS and DL+ are still updated). Seems that the audio codec is not supported in the AppImage of *DABstar*.

For example in Austria: `Mein Kinderradio` and `ERF Süd`, or `LoungeFM`. 

As you are located in Munich, unfortunately there are no HE-AAC v2 services in Bavaria on air (according to FMLIST), but do you have any change to test Austrian Mux I from Salzburg-Gaisberg (5B)? Or do you need an ETI file or even a RAW file?

I get tons of  `Warning: Unexpected channel configuration change` on the console.

![grafik](https://github.com/user-attachments/assets/faf3423d-ae4e-49b6-afc3-3c68636e9381)

See https://www.fmlist.org/sendertabelle/dab-st_more.php?inputLand=AUT&inputEn=A101
https://www.fmlist.org/sendertabelle/dab-st_more.php?inputLand=AUT&inputEn=A202

# other programs

## Qt-DAB

Qt-DAB (latest AppImage) has no problem with HE-AAC v2 audio.

![grafik](https://github.com/user-attachments/assets/a078a4da-f7d5-4997-8f45-cc414fc6a6fa)

# dablin_gtk

has no problem with HE-AAC v2 audio, too.

![grafik](https://github.com/user-attachments/assets/925dc624-a951-4f43-88b7-c58529e8523b)

**Comment by tomneda** [comment] 2024-10-04 16:18
@andimik thanks for hinting to this issue.

Unfortunately, I have no ensemble here where a service uses "Parametric Stereo" (which seems to need a v2 HE-AAC coded).
 
As it worked on Qt-DAB and the lower layers in DABstar are mainly original to Qt-DAB (at least at a former state) I compared the AppImages from latest DABstar and latest Qt-DAB. The main difference is that I build my DABstar with faad-AAC decoder, Qt-DAB uses the FDK-AAC decoder. This is switchable with cmake.

So, next I will try to deliver the AppImage with the FDK-AAC instead of faad. 

As I read, faad resp faad2 should work with PS/v2, it would be good I could test this. Salzburg-Gaisberg is too far away for my Omni-directional outdoor antenna (around 120km LOS), I am not able to receive a signal on 5B. Are you able to send me a RAW dump of one of your concerned ensembles? Some seconds should be enough. 

I am not aware to handle ETI files as input. If Qt-DAB was able to do that I do not somehow maintained it. My first main developing aspects to DABstar were more the SW-related "RF frontend", not the protocol/decoding stages.

Unfortunately, I made an upgrade from Xubuntu 22.04 to 24.04 and my AppImage build-system is currently not working anymore. So, a fix (changing to FDK-AAC, a.o.) could take a while.

**Comment by andimik** [comment] 2024-10-05 10:03
I have successfully built it from sources (branch `main`):

`sudo apt-get install libfdk-aac-dev` is required, otherwise it will fail.

`cmake .. -DAIRSPY=ON -DSDRPLAY_V2=OFF -DSDRPLAY_V3=OFF -DHACKRF=ON -DLIMESDR=OFF -DRTL_TCP=ON -DPLUTO=OFF -DUHD=OFF -DRTLSDR_LINUX=ON -DUSE_HBF=OFF -DDATA_STREAMER=OFF -DVITERBI_SSE=ON -DVITERBI_NEON=OFF -DFDK_AAC=ON` 

![grafik](https://github.com/user-attachments/assets/9d138e7d-c69e-4b3c-a03e-136eebe1825f)

But then the audio is at least not muting, but there are "gunshots" in the audio.


https://github.com/user-attachments/assets/f0efdc3a-d2bc-4d4f-bd66-02d3310b5468

**Comment by tomneda** [comment] 2024-10-05 12:45
@andimik: that is a strange effect. I used FDK-ACC (2.0.2-3) since yesterday on non-PS programs and they work fine.

I assume Qt-DAB or AbracaDABra were still working fine with the same service? Does the other PS programs behave the same with the "shotgun sound"?

I would appreciate if you could send a some second long RAW dump of this channel to look at this further here.

**Comment by andimik** [comment] 2024-10-05 13:05
Ok, I will prepare one.

**Comment by old-dab** [comment] 2024-10-05 14:21
Hi!
I can receive a lot of services with HE-AAC v2 codec on channel 7c from Groningen/Drenthe.
The DABstar AppImage doesn't work with these services. But if I compile DABstar myself, it works fine.
I have just compiled ist with FDK-ACC. Same problem as @andimik.

**Comment by andimik** [comment] 2024-10-06 11:33
These are 3 recordings (xml files incl. header) from Austria (DAB+ Austria Mux I, this is only one file, so the description was wrong) and Slovenia (R1 national and R2 West).

https://we.tl/t-3mvLPOeKcY

Please note that the link is only valid till 9th October.

**Comment by tomneda** [comment] 2024-10-06 17:44
@andimik your provided files helped me a lot. I could reproduce the problem clearly.

It turned out that the FDK-ACC lib provided with Ubuntu (still in 24.04) is somehow broken. If I rebuild the FDK-AAC lib with the same version (v2.0.2?) for my own then it worked very well.

So I used latest own-built v2.0.3 of the FDK-LIB and made a AppImage for that: [V2.7.0](https://github.com/tomneda/DABstar/releases/tag/V2.7.0)

Please check if it works now and close this issue afterwards if yes.

**Comment by tomneda** [comment] 2024-10-06 19:21
I investigate further with AbracaDABra and this seems to use `libfaad` and your files all working fine. I checked also that AbracaDABra uses the version  v2.11.1 from Xubuntu repository like DABstar uses and it still worked fine.

So, it seems the `libfaad` should also worked fine with DABstar but there seems to be an additional issue.

But the current recommended `FKD-ACC` should work fine for the first and I can look later why `libfaad` does not work well with DABstar.

**Comment by AustriaMV** [comment] 2024-10-09 19:37
With V2.7.0    on Linux Mint BR24 Sounds strange.

**Comment by tomneda** [comment] 2024-10-11 20:39
@AustriaMV : I found the problem of the strange BR24 sound. It happens only with mono signals which BR24 is. There happened two things: First was a buffer overrun while mixing the mono signal to the two audio channels (libfaad and FDK-AAC) and second a wrong indexing of the samples which causes that "Schlumpfsound" (FDK-AAC only).

I delivered a new version [V2.8.0](https://github.com/tomneda/DABstar/releases/tag/V2.8.0)

@andimik : Could you meanwhile retest the V2.7.0 or better now the V2.8.0?

**Comment by andimik** [comment] 2024-10-14 17:21
I've tested the 2.8 (compiled from sources).

The new problem now is, that all radio programs using HE-AAC v2 lose the stereo sound at all and PS is converted into mono :-(

**Comment by andimik** [comment] 2024-10-14 17:36
[Radio-Triglav-20241014-192307-00.00.30.325-00.00.43.468.latm.aac.zip](https://github.com/user-attachments/files/17367464/Radio-Triglav-20241014-192307-00.00.30.325-00.00.43.468.latm.aac.zip)


will sound this way:

https://github.com/user-attachments/assets/402ec548-cf71-4fcd-801c-b0bcb34a0ba5

**Comment by andimik** [comment] 2024-10-14 17:41
And it loses the higher frequencies (those for PS)

![grafik](https://github.com/user-attachments/assets/a9255a11-5bb2-4fc9-a36c-535a16b6a552)

will become

![grafik](https://github.com/user-attachments/assets/37ed8817-23ef-4f3c-8d72-a9fb06898271)

**Comment by tomneda** [comment] 2024-10-14 23:27
@andimik : That was strange: I tried your sample files with the different PS services and all (beside only speeches) have clear stereo sounds. One of the clearest stereo sounds I have extracted as wav-file (important!, see below) and put it also into the analyzer (audacity):

![Radio-Veselak_12D](https://github.com/user-attachments/assets/3feea105-29b1-4977-ae60-cb78e58b82ed)

You can see that it is no mono signal and the spectrum goes up to over 20 kHz. I could send you also the WAV file but I hope you can see it already.

But I hear your issue when I extract the "Dump AAC"  (or in Qt-DAB "Frame-Dump" o.a.) as .aac file. The services with PS are in mono and sounds a bit muffled, but non-PS are stereo. I have that simple explanation: The FDK-AAC or libfaad in DABstar are able to decode PS (v2) data but not our used music player (I use SMPlayer). This was also the same with older DABstar with libfaad decoder, but (as said) the acc data has to be extracted in front of the decoder.

So I guess this is a simple misunderstanding.

**Comment by andimik** [comment] 2024-10-15 06:02
I was not talking about external programs. I am aware, that some of them lose stereo and sample only at 24 kHz (like Audacity). The screenshots were taken with uncompressed audio of course.

I just downloaded the appImage 2.8 and there the audio is stereo for HE-AAC v2. Then back to the built version on my system - mono for HE-AAC v2.

My CMake config was that: 

[CMakeCache.txt](https://github.com/user-attachments/files/17373302/CMakeCache.txt)

Maybe I have done something wrong when building it?

**Comment by tomneda** [comment] 2024-10-15 22:31
@andimik: That is really "funny" what can happen with building software.

As a FDK-ACCv1 decoder is still able to decode FDK-AACv2 data with PS, but only in mono, I thought this is simply a audio-player problem first.

 I could see in your `CMakeCache.txt` that the FDK-AAC lib is searched in path `/usr/lib/x86_64-linux-gnu/` . 
`FDK_AAC_LIBRARIES:FILEPATH=/usr/lib/x86_64-linux-gnu/libfdk-aac.so`

This is the typical path for the library which are provide by e.g. Ubuntu repository.
Because this lib made issues (see above) I build it for my AppImage V2.7.0 for myself (see [README.md](https://github.com/tomneda/DABstar?tab=readme-ov-file#installing-on-linux).) This file is then typically located in `/usr/local/lib`. 

But I am not sure which lib is found first by `cmake` if both libraries exisits.

So, I would build the FDK-ACC library also for yourself and uninstall the one of the repository with 
`sudo apt-get remove libfdk-aac-dev`

To get sure that the library is found in the library search path, best call 
`sudo ldconfig` 
after building FDA-ACC (I forgot to mentioned that in the README.md).

Best you clear also the `CMakeCache.txt` to ensure a new library search with `cmake` (or clean up the build directory complete) before you build again.

**Comment by tomneda** [comment] 2024-11-01 00:25
@andimik : I guess this is working now, the reason seemed clear to me -> closing

**Closed by tomneda** 2024-11-01 00:25 UTC
Labels: bug
